//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.02 at 02:15:07 PM PDT 
//


package com.boomerang.vigilant.data;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="channel">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="generator" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="link" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="language" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="webMaster" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="copyright" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="pubDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="lastBuildDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="image">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="url" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="link" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="item" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="link" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="guid">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="isPermaLink" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="category" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="pubDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "channel"
})
@XmlRootElement(name = "rss")
public class Rss {

    @XmlElement(required = true)
    protected Rss.Channel channel;
    @XmlAttribute(name = "version")
    protected Double version;

    /**
     * Gets the value of the channel property.
     *
     * @return possible object is
     * {@link Rss.Channel }
     */
    public Rss.Channel getChannel() {
        return channel;
    }

    /**
     * Sets the value of the channel property.
     *
     * @param value allowed object is
     *              {@link Rss.Channel }
     */
    public void setChannel(Rss.Channel value) {
        this.channel = value;
    }

    /**
     * Gets the value of the version property.
     *
     * @return possible object is
     * {@link Integer }
     */
    public Double getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     *
     * @param value allowed object is
     *              {@link Integer }
     */
    public void setVersion(Double value) {
        this.version = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * <p>
     * <p>The following schema fragment specifies the expected content contained within this class.
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="generator" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="link" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="language" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="webMaster" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="copyright" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="pubDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="lastBuildDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="image">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="url" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="link" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="item" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="link" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="guid">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="isPermaLink" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="category" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="pubDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "generator",
            "title",
            "link",
            "language",
            "webMaster",
            "copyright",
            "pubDate",
            "lastBuildDate",
            "image",
            "item",
            "description"
    })
    public static class Channel {

        @XmlElement(required = true)
        protected String generator;
        @XmlElement(required = true)
        protected String title;
        @XmlElement(required = true)
        protected String link;
        @XmlElement(required = true)
        protected String language;
        @XmlElement(required = true)
        protected String webMaster;
        @XmlElement(required = true)
        protected String copyright;
        @XmlElement(required = true)
        protected String pubDate;
        @XmlElement(required = true)
        protected String lastBuildDate;
        @XmlElement(required = true)
        protected Rss.Channel.Image image;
        @XmlElement(required = true)
        protected List<Rss.Channel.Item> item;
        @XmlElement(required = true)
        protected String description;

        /**
         * Gets the value of the generator property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getGenerator() {
            return generator;
        }

        /**
         * Sets the value of the generator property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setGenerator(String value) {
            this.generator = value;
        }

        /**
         * Gets the value of the title property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getTitle() {
            return title;
        }

        /**
         * Sets the value of the title property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setTitle(String value) {
            this.title = value;
        }

        /**
         * Gets the value of the link property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getLink() {
            return link;
        }

        /**
         * Sets the value of the link property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setLink(String value) {
            this.link = value;
        }

        /**
         * Gets the value of the language property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getLanguage() {
            return language;
        }

        /**
         * Sets the value of the language property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setLanguage(String value) {
            this.language = value;
        }

        /**
         * Gets the value of the webMaster property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getWebMaster() {
            return webMaster;
        }

        /**
         * Sets the value of the webMaster property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setWebMaster(String value) {
            this.webMaster = value;
        }

        /**
         * Gets the value of the copyright property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getCopyright() {
            return copyright;
        }

        /**
         * Sets the value of the copyright property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setCopyright(String value) {
            this.copyright = value;
        }

        /**
         * Gets the value of the pubDate property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getPubDate() {
            return pubDate;
        }

        /**
         * Sets the value of the pubDate property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setPubDate(String value) {
            this.pubDate = value;
        }

        /**
         * Gets the value of the lastBuildDate property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getLastBuildDate() {
            return lastBuildDate;
        }

        /**
         * Sets the value of the lastBuildDate property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setLastBuildDate(String value) {
            this.lastBuildDate = value;
        }

        /**
         * Gets the value of the image property.
         *
         * @return possible object is
         * {@link Rss.Channel.Image }
         */
        public Rss.Channel.Image getImage() {
            return image;
        }

        /**
         * Sets the value of the image property.
         *
         * @param value allowed object is
         *              {@link Rss.Channel.Image }
         */
        public void setImage(Rss.Channel.Image value) {
            this.image = value;
        }

        /**
         * Gets the value of the item property.
         * <p>
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the item property.
         * <p>
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getItem().add(newItem);
         * </pre>
         * <p>
         * <p>
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Rss.Channel.Item }
         */
        public List<Rss.Channel.Item> getItem() {
            if (item == null) {
                item = new ArrayList<Rss.Channel.Item>();
            }
            return this.item;
        }

        /**
         * Gets the value of the description property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getDescription() {
            return description;
        }

        /**
         * Sets the value of the description property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setDescription(String value) {
            this.description = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * <p>
         * <p>The following schema fragment specifies the expected content contained within this class.
         * <p>
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="url" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="link" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
                "title",
                "url",
                "link"
        })
        public static class Image {

            @XmlElement(required = true)
            protected String title;
            @XmlElement(required = true)
            protected String url;
            @XmlElement(required = true)
            protected String link;

            /**
             * Gets the value of the title property.
             *
             * @return possible object is
             * {@link String }
             */
            public String getTitle() {
                return title;
            }

            /**
             * Sets the value of the title property.
             *
             * @param value allowed object is
             *              {@link String }
             */
            public void setTitle(String value) {
                this.title = value;
            }

            /**
             * Gets the value of the url property.
             *
             * @return possible object is
             * {@link String }
             */
            public String getUrl() {
                return url;
            }

            /**
             * Sets the value of the url property.
             *
             * @param value allowed object is
             *              {@link String }
             */
            public void setUrl(String value) {
                this.url = value;
            }

            /**
             * Gets the value of the link property.
             *
             * @return possible object is
             * {@link String }
             */
            public String getLink() {
                return link;
            }

            /**
             * Sets the value of the link property.
             *
             * @param value allowed object is
             *              {@link String }
             */
            public void setLink(String value) {
                this.link = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * <p>
         * <p>The following schema fragment specifies the expected content contained within this class.
         * <p>
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="link" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="guid">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="isPermaLink" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="category" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="pubDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
                "title",
                "link",
                "guid",
                "category",
                "pubDate",
                "description"
        })
        public static class Item {

            @XmlElement(required = true)
            protected String title;
            @XmlElement(required = true)
            protected String link;
            @XmlElement(required = true)
            protected Rss.Channel.Item.Guid guid;
            @XmlElement(required = true)
            protected String category;
            @XmlElement(required = true)
            protected String pubDate;
            @XmlElement(required = true)
            protected String description;

            /**
             * Gets the value of the title property.
             *
             * @return possible object is
             * {@link String }
             */
            public String getTitle() {
                return title;
            }

            /**
             * Sets the value of the title property.
             *
             * @param value allowed object is
             *              {@link String }
             */
            public void setTitle(String value) {
                this.title = value;
            }

            /**
             * Gets the value of the link property.
             *
             * @return possible object is
             * {@link String }
             */
            public String getLink() {
                return link;
            }

            /**
             * Sets the value of the link property.
             *
             * @param value allowed object is
             *              {@link String }
             */
            public void setLink(String value) {
                this.link = value;
            }

            /**
             * Gets the value of the guid property.
             *
             * @return possible object is
             * {@link Rss.Channel.Item.Guid }
             */
            public Rss.Channel.Item.Guid getGuid() {
                return guid;
            }

            /**
             * Sets the value of the guid property.
             *
             * @param value allowed object is
             *              {@link Rss.Channel.Item.Guid }
             */
            public void setGuid(Rss.Channel.Item.Guid value) {
                this.guid = value;
            }

            /**
             * Gets the value of the category property.
             *
             * @return possible object is
             * {@link String }
             */
            public String getCategory() {
                return category;
            }

            /**
             * Sets the value of the category property.
             *
             * @param value allowed object is
             *              {@link String }
             */
            public void setCategory(String value) {
                this.category = value;
            }

            /**
             * Gets the value of the pubDate property.
             *
             * @return possible object is
             * {@link String }
             */
            public String getPubDate() {
                return pubDate;
            }

            /**
             * Sets the value of the pubDate property.
             *
             * @param value allowed object is
             *              {@link String }
             */
            public void setPubDate(String value) {
                this.pubDate = value;
            }

            /**
             * Gets the value of the description property.
             *
             * @return possible object is
             * {@link String }
             */
            public String getDescription() {
                return description;
            }

            /**
             * Sets the value of the description property.
             *
             * @param value allowed object is
             *              {@link String }
             */
            public void setDescription(String value) {
                this.description = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * <p>
             * <p>The following schema fragment specifies the expected content contained within this class.
             * <p>
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="isPermaLink" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class Guid {

                @XmlAttribute(name = "isPermaLink")
                protected String isPermaLink;
                @XmlElement(required = true)
                protected String guid;

                /**
                 * Gets the value of the isPermaLink property.
                 *
                 * @return possible object is
                 * {@link String }
                 */
                public String getIsPermaLink() {
                    return isPermaLink;
                }

                /**
                 * Sets the value of the isPermaLink property.
                 *
                 * @param value allowed object is
                 *              {@link String }
                 */
                public void setIsPermaLink(String value) {
                    this.isPermaLink = value;
                }

                public String getGuid() {
                    return guid;
                }

                public void setGuid(String guid) {
                    this.guid = guid;
                }
            }

        }

    }

}
